// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GendRpc.proto

package gendgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d7175a2c0988cf4, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Reply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d7175a2c0988cf4, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RequestLong struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLong) Reset()         { *m = RequestLong{} }
func (m *RequestLong) String() string { return proto.CompactTextString(m) }
func (*RequestLong) ProtoMessage()    {}
func (*RequestLong) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d7175a2c0988cf4, []int{2}
}

func (m *RequestLong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLong.Unmarshal(m, b)
}
func (m *RequestLong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLong.Marshal(b, m, deterministic)
}
func (m *RequestLong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLong.Merge(m, src)
}
func (m *RequestLong) XXX_Size() int {
	return xxx_messageInfo_RequestLong.Size(m)
}
func (m *RequestLong) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLong.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLong proto.InternalMessageInfo

func (m *RequestLong) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReplyString struct {
	Json                 string   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyString) Reset()         { *m = ReplyString{} }
func (m *ReplyString) String() string { return proto.CompactTextString(m) }
func (*ReplyString) ProtoMessage()    {}
func (*ReplyString) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d7175a2c0988cf4, []int{3}
}

func (m *ReplyString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyString.Unmarshal(m, b)
}
func (m *ReplyString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyString.Marshal(b, m, deterministic)
}
func (m *ReplyString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyString.Merge(m, src)
}
func (m *ReplyString) XXX_Size() int {
	return xxx_messageInfo_ReplyString.Size(m)
}
func (m *ReplyString) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyString.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyString proto.InternalMessageInfo

func (m *ReplyString) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "gendgrpc.Request")
	proto.RegisterType((*Reply)(nil), "gendgrpc.Reply")
	proto.RegisterType((*RequestLong)(nil), "gendgrpc.RequestLong")
	proto.RegisterType((*ReplyString)(nil), "gendgrpc.ReplyString")
}

func init() { proto.RegisterFile("GendRpc.proto", fileDescriptor_0d7175a2c0988cf4) }

var fileDescriptor_0d7175a2c0988cf4 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x75, 0x4f, 0xcd, 0x4b,
	0x09, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x4f, 0xcd, 0x4b, 0x49,
	0x2f, 0x2a, 0x48, 0x56, 0xe2, 0xe4, 0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x12,
	0xe7, 0x62, 0x0d, 0x4a, 0x2d, 0xc8, 0xa9, 0x14, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x51, 0x92, 0xe5, 0xe2, 0x86, 0xaa, 0xf1, 0xc9, 0xcf,
	0x4b, 0xc7, 0x90, 0x56, 0x04, 0x49, 0x17, 0xe4, 0x54, 0x06, 0x97, 0x14, 0x65, 0xe6, 0xa5, 0x0b,
	0x09, 0x71, 0xb1, 0x64, 0x15, 0xe7, 0xe7, 0x81, 0x15, 0x70, 0x06, 0x81, 0xd9, 0x46, 0x85, 0x5c,
	0xec, 0x50, 0x07, 0x08, 0xe9, 0x72, 0xb1, 0xa6, 0xa7, 0xe6, 0x79, 0xa6, 0x08, 0x09, 0xea, 0xc1,
	0x1c, 0xa1, 0x07, 0x35, 0x5d, 0x8a, 0x1f, 0x59, 0xa8, 0x20, 0xa7, 0x52, 0x89, 0x41, 0xc8, 0x9c,
	0x8b, 0x35, 0xb5, 0xa2, 0xc0, 0x33, 0x45, 0x48, 0x14, 0x43, 0x39, 0xc8, 0x31, 0x52, 0xa2, 0x68,
	0x5a, 0x20, 0x8e, 0x50, 0x62, 0x48, 0x62, 0x03, 0xfb, 0xd4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xb7, 0x60, 0x99, 0x08, 0xfa, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GendRpcClient is the client API for GendRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GendRpcClient interface {
	GenId(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	ExpId(ctx context.Context, in *RequestLong, opts ...grpc.CallOption) (*ReplyString, error)
}

type gendRpcClient struct {
	cc *grpc.ClientConn
}

func NewGendRpcClient(cc *grpc.ClientConn) GendRpcClient {
	return &gendRpcClient{cc}
}

func (c *gendRpcClient) GenId(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/gendgrpc.GendRpc/genId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gendRpcClient) ExpId(ctx context.Context, in *RequestLong, opts ...grpc.CallOption) (*ReplyString, error) {
	out := new(ReplyString)
	err := c.cc.Invoke(ctx, "/gendgrpc.GendRpc/expId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GendRpcServer is the server API for GendRpc service.
type GendRpcServer interface {
	GenId(context.Context, *Request) (*Reply, error)
	ExpId(context.Context, *RequestLong) (*ReplyString, error)
}

func RegisterGendRpcServer(s *grpc.Server, srv GendRpcServer) {
	s.RegisterService(&_GendRpc_serviceDesc, srv)
}

func _GendRpc_GenId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GendRpcServer).GenId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gendgrpc.GendRpc/GenId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GendRpcServer).GenId(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GendRpc_ExpId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLong)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GendRpcServer).ExpId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gendgrpc.GendRpc/ExpId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GendRpcServer).ExpId(ctx, req.(*RequestLong))
	}
	return interceptor(ctx, in, info, handler)
}

var _GendRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gendgrpc.GendRpc",
	HandlerType: (*GendRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "genId",
			Handler:    _GendRpc_GenId_Handler,
		},
		{
			MethodName: "expId",
			Handler:    _GendRpc_ExpId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "GendRpc.proto",
}
